version: "v1.2.5"
GridXY: 1000 #//distance of grid
MinThicknessInDrill: 0.3
ScaleXY: 1.0
ScaleZ: 1.0
RadiusIn: 5 #//how many real drills in search radius
SearchRadius: 3000.0
IdwPow: 2.0 #//power of inverse weighting interpolation method
MinDrillDist: 1

drillWidth: 20
CanvasWidth: 1000
CanvasHeight: 700
CanvasMinThickness: 1
CanvasOffsetY: 0

Project: "泰州项目"
BlockResZ: 0.3 #//length of block < 1/3 min layer thickness  >0.1
OffX: -3592727.0
OffY: -499523.0
OffZ: 0.0
StdLen: 38   #//len of std layer num
MinDistance: 700 #// 泊松采样参数，min distance between points
MaxAttemptAdd: 7 #//  泊松采样参数， max attempts to add neighboring point
RealDrillDist: 90000
Layer: "./assets/taizhou/layer_info.dat"
Basic: "./assets/taizhou/basic_info.dat"
Boundary: "./assets/taizhou/boundary_info.dat"
StdLayer: "./assets/taizhou/std_layer_info.dat"

mysql:
  userName: "root"
  password: "1234"
  ip: "171.16.1.119"
  port: "3306"
  dbName: "test"
listen:
  port: "4399"  # some browser may forbid some specific port.

#  //阀厅项目
#  //const BlockResZ float64 = 0.2 //length of block < 1/3 min layer thickness  >0.1
#  //const StdLen int = 11 //len of std layer num
#  //const OffX float64 = -2624079
#  //const OffY float64 = -515645
#  //const OffZ float64 = -100 //fating
#  //const MinDistance =  10  // 泊松采样参数，min distance between points
#  //const MaxAttemptAdd = 15  //  泊松采样参数， max attempts to add neighboring point
#  //const RealDrillDist = 1000
#  //const Layer string = "/Users/zhangzhilong/go/src/probabDrill/assets/fating/layer_info.dat"
#  //const Basic string = "/Users/zhangzhilong/go/src/probabDrill/assets/fating/basic_info.dat"
#  //const Boundary string = "/Users/zhangzhilong/go/src/probabDrill/assets/fating/boundary_info.dat"
#  //const StdLayer string = "/Users/zhangzhilong/go/src/probabDrill/assets/fating/std_layer_info.dat"
#
#  //const Basic string = "C:/Users/张志龙/go/src/probabDrill/assets/basic_info.dat"
#  //const Layer string = "C:/Users/张志龙/go/src/probabDrill/assets/layer_info.dat"
#  //const Boundary string = "C:/Users/张志龙/go/src/probabDrill/assets/boundary_info.dat"
#  //const StdLayer string = "C:/Users/张志龙/go/src/probabDrill/assets/std_layer_info.dat"