version: "v1.2.5"
GridXY: 1000 #//distance of grid
MinThicknessInDrill: 0.3
ScaleXY: 1.0
ScaleZ: 1.0
RadiusIn: 5 #//how many real drills in search radius
SearchRadius: 3000.0
IdwPow: 2.0 #//power of inverse weighting interpolation method
MinDrillDist: 1

drillWidth: 20
CanvasWidth: 1000
CanvasHeight: 700
CanvasMinThickness: 1
CanvasOffsetY: 0

Project: "泰州项目"
BlockResZ: 0.3 #//length of block < 1/3 min layer thickness  >0.1
OffX: -3592727.0
OffY: -499523.0
OffZ: 0.0
StdLen: 38   #//len of std layer num
MinDistance: 700 #// 泊松采样参数，min distance between points
MaxAttemptAdd: 7 #//  泊松采样参数， max attempts to add neighboring point
RealDrillDist: 90000
Layer: "/Users/zhangzhilong/go/src/probabDrill/assets/layer_info.dat"
Basic: "/Users/zhangzhilong/go/src/probabDrill/assets/basic_info.dat"
Boundary: "/Users/zhangzhilong/go/src/probabDrill/assets/boundary_info.dat"
StdLayer: "/Users/zhangzhilong/go/src/probabDrill/assets/std_layer_info.dat"
