basePath: /v1
definitions:
  model.Drill:
    properties:
      layerHeights:
        description: layer's bottom height.
        items:
          type: number
        type: array
      layers:
        description: layers' seq id.
        items:
          type: integer
        type: array
      name:
        type: string
      x:
        type: number
    type: object
host: 171.16.1.107:4399
info:
  contact: {}
  license:
    name: 中山大学岩土工程与信息技术研究中心
  title: 基于沉积序列的三维地层概率模型研究
  version: "1.0"
paths:
  /err/DrillAroundPeCloud:
    get:
      description: 真实钻孔周围虚拟钻孔的百分比误差，应用反距离插值方法 [][]float64{xs, ys, pes}
      operationId: DrillAroundPeCloud
      parameters:
      - description: TZZK06
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 真实钻孔周围500米虚拟钻孔的百分比误差
      tags:
      - 误差评估
  /err/DrillAroundPeCloudM1:
    get:
      description: 真实钻孔周围虚拟钻孔的百分比误差，应用反距离插值方法 [][]float64{xs, ys, pes}
      operationId: DrillAroundPeCloudM1
      parameters:
      - description: TZZK06
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 真实钻孔周围500米虚拟钻孔的百分比误差
      tags:
      - 误差评估
  /err/GetAvgPEByLayerIDW:
    get:
      description: 获取研究区域内钻孔钻孔分层PE，应用反距离插值方法
      operationId: GetAvgPEByLayerIDW
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 钻孔分层PE
      tags:
      - 误差评估
  /err/GetAvgPEByLayerM1:
    get:
      description: 获取研究区域内钻孔钻孔分层PE，应用反距离插值方法
      operationId: GetAvgPEByLayerM1
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 钻孔分层PE
      tags:
      - 误差评估
  /err/GetStudyAreaAvgDrillPEIdw:
    get:
      description: 获取研究区域内钻孔平均百分比误差，需要自行获取研究区域的矩形边界
      operationId: GetStudyAreaAvgDrillPEIdw
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取研究区域内钻孔平均百分比误差反距离插值方法
      tags:
      - 误差评估
  /err/GetStudyAreaAvgDrillPEM1:
    get:
      description: 获取研究区域内钻孔平均百分比误差，需要自行获取研究区域的矩形边界
      operationId: GetStudyAreaAvgDrillPEM1
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取研究区域内钻孔平均百分比误差概率模型构建方法
      tags:
      - 误差评估
  /gen/GenIdwDrill:
    get:
      description: 在特定位置生成钻孔数据，采用反距离插值方法
      operationId: GenIdwDrill
      parameters:
      - description: position
        in: query
        name: x
        required: true
        type: number
      - description: position
        in: query
        name: "y"
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成反距离插值的虚拟钻孔数据
      tags:
      - 服务
  /gen/GenM1Drill:
    get:
      description: 在特定位置生成钻孔数据，采用基于沉积序列的三维地层概率模型构建方法
      operationId: GenM1Drill
      parameters:
      - description: position
        in: query
        name: x
        required: true
        type: number
      - description: position
        in: query
        name: "y"
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成概率模型虚拟钻孔数据
      tags:
      - 服务
  /gen/GenM1DrillSecond:
    get:
      description: 在特定位置生成钻孔数据，采用基于沉积序列的三维地层概率模型构建方法
      operationId: GenM1DrillSecond
      parameters:
      - description: position
        in: query
        name: x
        required: true
        type: number
      - description: position
        in: query
        name: "y"
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 生成次大概率模型虚拟钻孔数据
      tags:
      - 服务
  /utils/GetRec:
    get:
      description: 获取研究区域内左下和右上角点坐标[x1,y1,x2,y2]
      operationId: GetRec
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取研究区域内左下和右上角点坐标
      tags:
      - 工具类
  /utils/IsValidPoint:
    get:
      consumes:
      - multipart/form-data
      description: 钻孔位置是否在边界内
      operationId: IsValidPoint
      parameters:
      - description: x
        in: query
        name: x
        required: true
        type: number
      - description: "y"
        in: query
        name: "y"
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: '{"true"}'
          schema:
            type: string
      summary: 钻孔位置是否有效
      tags:
      - 工具类
  /utils/ProbBlocks:
    get:
      description: 获取研究区域内不同深度范围内blocks出现的概率
      operationId: ProbBlocks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 研究区域内block概率矩阵
      tags:
      - 工具类
  /utils/queryDrill:
    get:
      consumes:
      - multipart/form-data
      description: 钻孔位置是否在边界内
      operationId: QueryDrill
      parameters:
      - description: TZZK06
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: return queried drill, TZZK05
          schema:
            items:
              $ref: '#/definitions/model.Drill'
            type: array
      summary: 钻孔位置是否有效
      tags:
      - 工具类
swagger: "2.0"
